export { Button } from './Button/Button'
export { Grid } from './Grid/Grid'
// export { Header } from '../../../components/header/header'
export { HeroBlock } from './HeroBlock/HeroBlock'
export { HeroPoster } from './HeroBlock/HeroPoster'
export { HeroInfo } from './HeroBlock/HeroInfo'
export { LoadingTape } from './LoadingTape/LoadingTape'
export { Tabs } from './Tabs/Tabs'
export { Thumb } from './Thumb/Thumb'
export { Text } from './Text/Text'
export { Separator } from './Separator/Separator'
